trainer:
  name: parallel_ea
  n_iterations: 1000
  params:
    sigma: 1
    alpha: 0.008
    population_size: 30
    tournament_size: 10
    mutation_probability: 1
    n_replacements: 20
dataloader:
  dataset_name: circular
  use_batch: true
  batch_size: 100
  n_batches: 10
network:
  name: circular_problem_perceptron
  loss: bceloss
general: !include general.yml