trainer:
  name: alternating_ea
  n_iterations: 1000
  params:
    sigma: 0.05
    alpha: 0.001
    population_size: 50
    tournament_size: 2
    mutation_probability: 0.9
    n_replacements: 5
dataloader:
  dataset_name: mnist
  use_batch: true
  batch_size: 500
  n_batches: 1
network:
  name: four_layer_perceptron
  loss: bceloss
general: !include general.yml
